#!/usr/bin/env bash
set -uo pipefail

# Self-test for agentTooling's own permission policy: ONE file, .claude/settings.json,
# TRACKED and wholly generated by hooks/wire-settings.py --self --write — the PreToolUse
# hook, the Edit/Bash deny rules, the hooks/ ask rule and the sandbox block — whose hook
# command is guarded to a silent no-op where ${CLAUDE_PROJECT_DIR}/hooks/allow-repo-commands.sh
# does not exist (self/features/self-cloud-bootstrap; it reverses self-settings-untracked,
# and replaces that feature's round-1 SessionStart bootstrap on live evidence). Run by
# self/gate.sh, or by hand: bash self/tests/self-settings.sh
#
# Stages the real hooks/, self/worktree-setup.sh, self/gate.sh, .gitignore and the tracked
# file into throwaway git repos under mktemp -d and asserts, in order:
#   0. the generator writes exactly one file into an empty directory, .claude/settings.json,
#      carrying no permissions.allow and no SessionStart entry, its one PreToolUse command
#      the guarded one;
#   A. in a fresh standalone worktree the tracked file is byte for byte what the generator
#      writes, `--self --check` says in-sync, and the setup hook — run the way
#      feature-start.sh runs it — exits 0 and writes nothing at all;
#   B. self/gate.sh's settings check passes on that file, FAILS on a missing and on a
#      drifted one, naming the file and the exact regenerate command each time, and passes
#      again once that command has run, the worktree clean;
#   C. in the VENDORED layout (agentTooling/ one directory inside a consuming repo, no
#      .git of its own) the setup hook writes nothing; the shipped
#      agentTooling/.claude/settings.json is byte for byte the generator's and
#      `--self --check` and the gate pass on it; a drifted or missing one FAILS, saying
#      the fix is upstream and naming no local regenerate; --write writes nothing over
#      either; and the consuming repo's own root file still names the vendored hook path;
#   D. this checkout tracks .claude/settings.json and nothing else under .claude/, byte
#      for byte the generator's, and .gitignore covers .claude/settings.local.json —
#      Claude Code's own per-user file of "don't ask again" grants — and not the policy;
#   E. the OS sandbox block (self/features/runner-sandbox) in each layout: the self file
#      carries it with `enabled` at wire-settings.py's SANDBOX_ENABLED switch (OFF since
#      self/features/sandbox-consumer-reads), fail-closed and no unsandboxed retry, the
#      secret denyRead paths and the package domains; a hand-added domain there fails the
#      gate and the regenerate removes it; the vendored layout's root file carries the
#      same owned settings, a consumer's own domain survives a re-run of the wiring with
#      the generator's domains unioned in after it, and a consumer's `enabled` flipped by
#      hand against the switch is set back to it;
#   F. the tracked hook command, taken from the generated file and run the way Claude Code
#      runs a command hook (`sh -c`, from the project directory, CLAUDE_PROJECT_DIR set, the
#      PreToolUse payload on stdin — which the guarded second command inherits from the
#      shell): (a) CLAUDE_PROJECT_DIR the consuming repo's root, which has no hooks/ —
#      exit 0, empty stdout and stderr, nothing written; (b) CLAUDE_PROJECT_DIR the
#      vendored agentTooling/ and (c) a standalone checkout — `python3 -c 'print(1)'` is
#      denied; and standalone `--self --check` is in-sync. The payload carries no
#      session_id, so the hook keeps no escalation counter (state_path() is None) and
#      denies every time; its TMPDIR is a scratch directory asserted empty afterwards;
#   G. under GATE_RESUME=1 (which feature-start.sh and the runners set) the settings check
#      runs with record_fresh, so it is never resumed (self/features/session-start-precision):
#      after a pass, a deleted working copy and a drifted one still FAIL it, and no
#      gate-state record is ever written for it. The file is tracked now, so the tree sha
#      changes with it too; G4 — no record — is the assertion that pins record_fresh itself.
#
# The staged gate runs with GATE_RESUME unset everywhere but G, which sets it explicitly
# on each of its own runs. feature-start.sh and the runners export GATE_RESUME=1: an
# inherited one let the staged gate reuse its first recorded PASS for every later run on
# the same tree, and B and E went red for a gate that never re-checked.
# No model, no network; a few seconds.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/self-settings.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT
TMP="$(cd "$TMP" && pwd -P)"
unset GATE_RESUME

# What is under test, and where
SETTINGS_REL=".claude/settings.json"
LOCAL_REL=".claude/settings.local.json"
SETTINGS_DIR_REL=".claude"
SETTINGS_NAME="settings.json"
HOOK_FILES=(policy.py wire-settings.py allow-repo-commands.sh)
SELF_SCRIPTS=(worktree-setup.sh gate.sh)
# The tracked hook command, as the brief fixed it: a no-op where the script is absent, the
# script itself otherwise (it reads the payload on stdin, which `test` leaves alone).
HOOK_GUARDED_COMMAND='test ! -f "${CLAUDE_PROJECT_DIR}/hooks/allow-repo-commands.sh" || "${CLAUDE_PROJECT_DIR}/hooks/allow-repo-commands.sh"'
# The consuming repo's own wiring at its root, as sync-plans.sh writes it
CONSUMER_HOOK_COMMAND='${CLAUDE_PROJECT_DIR}/agentTooling/hooks/allow-repo-commands.sh'
# The section self/gate.sh writes for its settings check, and the command a failure must
# name — the one a human runs, with this checkout's absolute paths filled in.
GATE_SECTION="## permission policy wired into .claude/settings.json"
REGEN_RE='python3 -B [^ ;]*/hooks/wire-settings\.py --self --repo [^ ;)]* --write'
VENDOR_DIR_NAME="agentTooling"
# Statuses --check prints first on its line
STATUS_IN_SYNC="in-sync"
STATUS_MISSING="missing"
STATUS_UNWIRED="UNWIRED"
# What a vendored failure must say instead of a local regenerate
UPSTREAM_WORD="upstream"
# The hook's verdict for a command it cannot read, as it prints it
DENY_DECISION='"permissionDecision": "deny"'
UNREADABLE_COMMAND="python3 -c 'print(1)'"
# Section G: the resume switch self/gate.sh reads, where its per-check records go, and the
# record file name that check's label would get (gate_state_file's character mapping of
# the gate's label "permission policy wired into .claude/settings.json").
GATE_RESUME_ON="1"
GATE_STATE_REL="self/gate-state"
SETTINGS_STATE_NAME="permission_policy_wired_into__claude_settings_json"

fails=0
ok()   { echo "  ok    $1"; }
fail() { echo "  FAIL  $1"; fails=$((fails + 1)); }
check() { if eval "$2"; then ok "$1"; else fail "$1"; fi; }

# stage <dir> — the pieces of agentTooling this test drives, copied from this checkout,
# with the generator's settings file committed as the real checkout commits it.
stage() {
  mkdir -p "$1/hooks" "$1/self" "$1/$SETTINGS_DIR_REL"
  for f in "${HOOK_FILES[@]}"; do cp "$HERE/hooks/$f" "$1/hooks/$f"; done
  for f in "${SELF_SCRIPTS[@]}"; do cp "$HERE/self/$f" "$1/self/$f"; done
  cp "$HERE/.gitignore" "$1/.gitignore"
  cp "$EXPECTED" "$1/$SETTINGS_REL"
  chmod +x "$1"/self/*.sh "$1/hooks/allow-repo-commands.sh"
}
# commit_repo <dir> — make it a repo on main with everything committed.
commit_repo() {
  git -C "$1" init -q
  git -C "$1" symbolic-ref HEAD refs/heads/main
  git -C "$1" config user.email test@example.invalid
  git -C "$1" config user.name "self-settings test"
  git -C "$1" add -A
  git -C "$1" commit -q -m init
}
# run_setup <worktree> <repo dir inside it> — the hook, as feature-start.sh runs it: from
# the worktree's toplevel, by the absolute path of the worktree's own copy.
run_setup() { ( cd "$1" && "$2/self/worktree-setup.sh" ) >/dev/null 2>&1; }
# run_gate <repo dir> / gate_section <repo dir> — self/gate.sh's settings section. The
# staged checkout carries none of the other suites, so every other section fails; only
# this one is read.
run_gate() { "$1/self/gate.sh" >/dev/null 2>&1; }
# run_gate_resumed <repo dir> — the same, with GATE_RESUME=1 set for this one run (G only;
# everywhere else it stays unset, above).
run_gate_resumed() { GATE_RESUME="$GATE_RESUME_ON" "$1/self/gate.sh" >/dev/null 2>&1; }
gate_section() {
  awk -v want="$GATE_SECTION" '
    $0 == want { on = 1; next }
    on && /^## / { exit }
    on && /^# VERDICT/ { exit }
    on { print }
  ' "$1/self/gate-report.txt" 2>/dev/null
}
gate_exit() { gate_section "$1" | sed -n 's/^exit: //p' | head -n 1; }
# regen_command <text> — the regenerate command a failure names, or nothing.
regen_command() { grep -oE "$REGEN_RE" <<<"$1" | head -n 1; }
# tree_state <dir> — every path git sees under <dir>, ignored and untracked included, with
# its status: what "nothing written" is compared by.
tree_state() { git -C "$1" status --porcelain --ignored --untracked-files=all 2>/dev/null; }
# self_check <repo dir> — `--self --check` over it, its one line on stdout; rc in $?.
self_check() { python3 -B "$1/hooks/wire-settings.py" --self --repo "$1" --check 2>&1; }
self_write() { python3 -B "$1/hooks/wire-settings.py" --self --repo "$1" --write >/dev/null 2>&1; }
# settings_field <file> <hook-command|shape> — the one PreToolUse command, or the shape the
# contract pins: whether permissions.allow and a SessionStart entry are present.
settings_field() {
  python3 -B - "$@" <<'PY'
import json, sys
path, what = sys.argv[1], sys.argv[2]
try:
    with open(path) as f:
        settings = json.load(f)
except (OSError, ValueError):
    sys.exit(0)
hooks = settings.get("hooks") or {}
if what == "shape":
    print("allow=%s sessionstart=%s events=%s" % (
        "allow" in (settings.get("permissions") or {}), "SessionStart" in hooks,
        ",".join(sorted(hooks))))
elif what == "hook-command":
    commands = [h.get("command") for e in hooks.get("PreToolUse") or []
                for h in (e or {}).get("hooks") or []]
    if len(commands) == 1:
        print(commands[0])
PY
}

echo "self-settings"

# ── 0. what the generator writes into an empty directory: THE file ───────────
EXPECTED_DIR="$TMP/expected"
mkdir -p "$EXPECTED_DIR"
python3 -B "$HERE/hooks/wire-settings.py" --self --repo "$EXPECTED_DIR" --write >/dev/null 2>&1
EXPECTED="$EXPECTED_DIR/$SETTINGS_REL"
check "0a. the generator writes the whole policy into $SETTINGS_REL" '[[ -s "$EXPECTED" ]]'
check "0b. ... and nothing else: $SETTINGS_DIR_REL/ holds that one file (got '$(ls -A "$EXPECTED_DIR/$SETTINGS_DIR_REL" 2>/dev/null | tr '\n' ' ')')" \
  '[[ "$(ls -A "$EXPECTED_DIR/$SETTINGS_DIR_REL" 2>/dev/null)" == "$SETTINGS_NAME" ]]'
check "0c. it carries no permissions.allow and no SessionStart entry, only PreToolUse (got '$(settings_field "$EXPECTED" shape)')" \
  '[[ "$(settings_field "$EXPECTED" shape)" == "allow=False sessionstart=False events=PreToolUse" ]]'
HOOK_CMD="$(settings_field "$EXPECTED" hook-command)"
check "0d. its one PreToolUse command is the guarded one (got '$HOOK_CMD')" \
  '[[ "$HOOK_CMD" == "$HOOK_GUARDED_COMMAND" ]]'

# ── A. a fresh standalone worktree is born wired, and the setup hook writes nothing
SA="$TMP/standalone"
WT="$TMP/standalone-wt"
stage "$SA"
commit_repo "$SA"
git -C "$SA" worktree add -q "$WT" -b feat
check "A1. the fresh worktree's tracked $SETTINGS_REL is byte for byte the generator's" \
  'cmp -s "$WT/$SETTINGS_REL" "$EXPECTED"'
a_check="$(self_check "$WT")"; rc=$?
check "A2. ... and --self --check says $STATUS_IN_SYNC (got $rc: '$a_check')" \
  '[[ $rc -eq 0 && "$a_check" == "$STATUS_IN_SYNC"* ]]'
before="$(tree_state "$WT")"
run_setup "$WT" "$WT"; rc=$?
check "A3. the setup hook exits 0 (got $rc)" '[[ $rc -eq 0 ]]'
check "A4. ... and writes nothing: no $LOCAL_REL, the tree as it was" \
  '[[ ! -e "$WT/$LOCAL_REL" && "$(tree_state "$WT")" == "$before" ]]'

# ── B. the gate fails without the file, or with a drifted one, and names the fix
run_gate "$WT"
check "B1. the gate's settings check passes on the tracked file (got '$(gate_exit "$WT")')" \
  '[[ "$(gate_exit "$WT")" == "0" ]]'
rm -f "$WT/$SETTINGS_REL"
run_gate "$WT"
missing_out="$(gate_section "$WT")"
check "B2. ... FAILS when the file is missing (got '$(gate_exit "$WT")')" '[[ "$(gate_exit "$WT")" == "1" ]]'
check "B3. ... naming the file and the regenerate command, with this checkout's paths" \
  '[[ "$missing_out" == *"$SETTINGS_REL"* && "$(regen_command "$missing_out")" == *"--repo $WT --write" ]]'
printf '{}\n' > "$WT/$SETTINGS_REL"
run_gate "$WT"
drift_out="$(gate_section "$WT")"
check "B4. ... FAILS when the file has drifted from the generator (got '$(gate_exit "$WT")')" \
  '[[ "$(gate_exit "$WT")" == "1" ]]'
check "B5. ... naming the file and the same command" \
  '[[ "$drift_out" == *"$SETTINGS_REL"* && -n "$(regen_command "$drift_out")" && "$(regen_command "$drift_out")" == "$(regen_command "$missing_out")" ]]'
read -r -a regen <<<"$(regen_command "$drift_out")"
if (( ${#regen[@]} )); then "${regen[@]}" >/dev/null 2>&1; fi
run_gate "$WT"
check "B6. running that command makes the check pass again, the worktree clean (got '$(gate_exit "$WT")')" \
  '[[ "$(gate_exit "$WT")" == "0" ]] && cmp -s "$WT/$SETTINGS_REL" "$EXPECTED" && [[ -z "$(git -C "$WT" status --porcelain)" ]]'

# ── C. a vendored agentTooling ships the file; the fix for it is upstream ─────
CONSUMER="$TMP/consumer"
CWT="$TMP/consumer-wt"
stage "$CONSUMER/$VENDOR_DIR_NAME"
printf 'a consuming repo\n' > "$CONSUMER/README.md"
# The consuming repo's own wiring, at ITS root, as sync-plans.sh writes it.
python3 -B "$CONSUMER/$VENDOR_DIR_NAME/hooks/wire-settings.py" --repo "$CONSUMER" --write >/dev/null 2>&1
commit_repo "$CONSUMER"
git -C "$CONSUMER" worktree add -q "$CWT" -b feat
VAT="$CWT/$VENDOR_DIR_NAME"
before="$(tree_state "$CWT")"
run_setup "$CWT" "$VAT"; rc=$?
check "C1. the setup hook exits 0 in the vendored layout (got $rc)" '[[ $rc -eq 0 ]]'
check "C2. ... and writes nothing: no nested $LOCAL_REL, the tree as it was" \
  '[[ ! -e "$VAT/$LOCAL_REL" && "$(tree_state "$CWT")" == "$before" ]]'
check "C3. the consuming repo's root file names the vendored hook path" \
  '[[ "$(settings_field "$CWT/$SETTINGS_REL" hook-command)" == "$CONSUMER_HOOK_COMMAND" ]]'
check "C4. the shipped $VENDOR_DIR_NAME/$SETTINGS_REL is byte for byte the generator's" \
  'cmp -s "$VAT/$SETTINGS_REL" "$EXPECTED"'
c_check="$(self_check "$VAT")"; rc=$?
check "C5. ... and --self --check there says $STATUS_IN_SYNC (got $rc: '$c_check')" \
  '[[ $rc -eq 0 && "$c_check" == "$STATUS_IN_SYNC"* ]]'
run_gate "$VAT"
check "C6. ... and so does self/gate.sh's settings check (got '$(gate_exit "$VAT")')" \
  '[[ "$(gate_exit "$VAT")" == "0" ]]'
printf '{}\n' > "$VAT/$SETTINGS_REL"
vdrift_out="$(self_check "$VAT")"; rc=$?
check "C7. a drifted vendored file fails --self --check as $STATUS_UNWIRED (got $rc: '$vdrift_out')" \
  '[[ $rc -eq 1 && "$vdrift_out" == "$STATUS_UNWIRED"* && "$vdrift_out" == *"$SETTINGS_REL"* ]]'
check "C8. ... saying the fix is $UPSTREAM_WORD, with no local regenerate command" \
  '[[ "$vdrift_out" == *"$UPSTREAM_WORD"* && "$vdrift_out" != *"--repo $VAT"* ]]'
self_write "$VAT"
check "C9. --self --write writes nothing over it" '[[ "$(cat "$VAT/$SETTINGS_REL")" == "{}" ]]'
rm -f "$VAT/$SETTINGS_REL"
vmissing_out="$(self_check "$VAT")"; rc=$?
check "C10. a missing vendored file fails --self --check as $STATUS_MISSING, the fix $UPSTREAM_WORD (got $rc: '$vmissing_out')" \
  '[[ $rc -eq 1 && "$vmissing_out" == "$STATUS_MISSING"* && "$vmissing_out" == *"$UPSTREAM_WORD"* && "$vmissing_out" != *"--repo $VAT"* ]]'
before="$(tree_state "$CWT")"
self_write "$VAT"
check "C11. ... and --self --write writes nothing into its absence" \
  '[[ ! -e "$VAT/$SETTINGS_REL" && "$(tree_state "$CWT")" == "$before" ]]'
cp "$EXPECTED" "$VAT/$SETTINGS_REL"

# ── D. this checkout tracks the policy and only the policy ───────────────────
check "D1. $SETTINGS_REL is the one file tracked under $SETTINGS_DIR_REL/ here (got '$(git -C "$HERE" ls-files -- "$SETTINGS_DIR_REL" | tr '\n' ' ')')" \
  '[[ "$(git -C "$HERE" ls-files -- "$SETTINGS_DIR_REL")" == "$SETTINGS_REL" ]]'
check "D2. ... and what git holds is byte for byte the generator's" \
  'cmp -s <(git -C "$HERE" show ":$SETTINGS_REL" 2>/dev/null) "$EXPECTED"'
check "D3. .gitignore covers $LOCAL_REL" 'git -C "$HERE" check-ignore -q --no-index -- "$LOCAL_REL"'
check "D4. ... and not $SETTINGS_REL" '! git -C "$HERE" check-ignore -q --no-index -- "$SETTINGS_REL"'

# ── E. the sandbox block, in each layout ─────────────────────────────────────
# Self layout: the file is generated, so the block is there and a hand-widened domain
# list is drift the gate refuses. Vendored layout: the consuming repo's root file is
# merged, so the block is there too and the repo's own domain survives a re-run of the
# wiring with the generator's entries unioned in beside it.
# sandbox_field <settings file> <owned|denyRead|domains|add-domain D|only-domain D|flip-enabled>
# — prints one space-joined field of the sandbox block, or edits it in place.
sandbox_field() {
  python3 -B - "$@" <<'PY'
import json, sys
path, what = sys.argv[1], sys.argv[2]
with open(path) as f:
    settings = json.load(f)
box = settings.get("sandbox") or {}
domains = (box.get("network") or {}).get("allowedDomains") or []
if what == "owned":
    print(" ".join("%s=%s" % (k, box.get(k))
                   for k in ("enabled", "failIfUnavailable", "allowUnsandboxedCommands")))
elif what == "denyRead":
    print(" ".join((box.get("filesystem") or {}).get("denyRead") or []))
elif what == "domains":
    print(" ".join(domains))
elif what == "flip-enabled":
    settings.setdefault("sandbox", {})["enabled"] = not box.get("enabled")
    with open(path, "w") as f:
        json.dump(settings, f, indent=2)
        f.write("\n")
else:
    new = domains + [sys.argv[3]] if what == "add-domain" else [sys.argv[3]]
    settings.setdefault("sandbox", {}).setdefault("network", {})["allowedDomains"] = new
    with open(path, "w") as f:
        json.dump(settings, f, indent=2)
        f.write("\n")
PY
}
OWN_DOMAIN="internal.example.invalid"
# wire-settings.py's SANDBOX_ENABLED switch, as Python prints it; flip with the constant
SANDBOX_ENABLED_EXPECTED="False"
check "E1. the self worktree's file carries the block with enabled=$SANDBOX_ENABLED_EXPECTED, fail-closed and no unsandboxed retry still written" \
  '[[ "$(sandbox_field "$WT/$SETTINGS_REL" owned)" == "enabled=$SANDBOX_ENABLED_EXPECTED failIfUnavailable=True allowUnsandboxedCommands=False" ]]'
check "E2. ... denies reads of the three secret paths" \
  '[[ "$(sandbox_field "$WT/$SETTINGS_REL" denyRead)" == "~/.ssh ~/.aws ~/.config/gh" ]]'
check "E3. ... and allows registry.npmjs.org and pypi.org among its domains" \
  '[[ " $(sandbox_field "$WT/$SETTINGS_REL" domains) " == *" registry.npmjs.org "* && " $(sandbox_field "$WT/$SETTINGS_REL" domains) " == *" pypi.org "* ]]'
sandbox_field "$WT/$SETTINGS_REL" add-domain "$OWN_DOMAIN"
run_gate "$WT"
check "E4. a domain hand-added to the file fails the gate's settings check (got '$(gate_exit "$WT")')" \
  '[[ "$(gate_exit "$WT")" == "1" ]]'
self_write "$WT"
check "E5. ... and the regenerate puts the generated bytes back" 'cmp -s "$WT/$SETTINGS_REL" "$EXPECTED"'
check "E6. the vendored layout's root file carries the same owned settings" \
  '[[ "$(sandbox_field "$CWT/$SETTINGS_REL" owned)" == "$(sandbox_field "$EXPECTED" owned)" ]]'
sandbox_field "$CWT/$SETTINGS_REL" only-domain "$OWN_DOMAIN"
python3 -B "$VAT/hooks/wire-settings.py" --repo "$CWT" --write >/dev/null 2>&1
check "E7. ... where a consumer's own domain survives the wiring, first, the generator's unioned in after" \
  '[[ -n "$(sandbox_field "$EXPECTED" domains)" && "$(sandbox_field "$CWT/$SETTINGS_REL" domains)" == "$OWN_DOMAIN $(sandbox_field "$EXPECTED" domains)" ]]'
sandbox_field "$CWT/$SETTINGS_REL" flip-enabled
python3 -B "$VAT/hooks/wire-settings.py" --repo "$CWT" --write >/dev/null 2>&1
check "E8. ... and a consumer's enabled flipped by hand against the switch is set back to enabled=$SANDBOX_ENABLED_EXPECTED" \
  '[[ "$(sandbox_field "$CWT/$SETTINGS_REL" owned)" == "enabled=$SANDBOX_ENABLED_EXPECTED failIfUnavailable=True allowUnsandboxedCommands=False" ]]'
# Put the consumer's root file back to what C committed, so F's "nothing written" starts clean.
git -C "$CWT" checkout -q -- "$SETTINGS_REL"

# ── F. the tracked hook command, run as Claude Code runs a command hook ───────
HOOK_TMP="$TMP/hook-tmp"
mkdir -p "$HOOK_TMP"
# run_hook <project dir> — the command through `sh -c` from that directory, with
# CLAUDE_PROJECT_DIR set to it and a PreToolUse payload for UNREADABLE_COMMAND (cwd the
# project dir) on stdin; stdout and stderr to $TMP/hook.out and $TMP/hook.err.
run_hook() {
  printf '{"tool_name":"Bash","tool_input":{"command":"%s"},"cwd":"%s"}' \
    "$UNREADABLE_COMMAND" "$1" >"$TMP/hook.in"
  ( cd "$1" && CLAUDE_PROJECT_DIR="$1" TMPDIR="$HOOK_TMP" sh -c "$HOOK_CMD" ) \
    <"$TMP/hook.in" >"$TMP/hook.out" 2>"$TMP/hook.err"
}
# (a) the consuming repo's root: no hooks/allow-repo-commands.sh there
before="$(tree_state "$CWT")"
run_hook "$CWT"; rc=$?
check "Fa1. CLAUDE_PROJECT_DIR=the consuming repo's root: exits 0 (got $rc)" '[[ -n "$HOOK_CMD" && $rc -eq 0 ]]'
check "Fa2. ... prints nothing at all (stdout: '$(cat "$TMP/hook.out")', stderr: '$(cat "$TMP/hook.err")')" \
  '[[ ! -s "$TMP/hook.out" && ! -s "$TMP/hook.err" ]]'
check "Fa3. ... and writes nothing" '[[ "$(tree_state "$CWT")" == "$before" ]]'
# (b) the vendored agentTooling/: its own hooks/ is there, and the session that loads this
# file is one launched inside it (NOTES.md → "The open question (live)", ruling 2)
run_hook "$VAT"; rc=$?
check "Fb1. CLAUDE_PROJECT_DIR=$VENDOR_DIR_NAME/: $UNREADABLE_COMMAND is denied (got $rc: '$(cat "$TMP/hook.out")')" \
  '[[ $rc -eq 0 ]] && grep -qF "$DENY_DECISION" "$TMP/hook.out"'
check "Fb2. ... and nothing is written in the consumer" '[[ "$(tree_state "$CWT")" == "$before" ]]'
# (c) a standalone checkout, fresh
WT2="$TMP/standalone-wt2"
git -C "$SA" worktree add -q "$WT2" -b fresh
before="$(tree_state "$WT2")"
run_hook "$WT2"; rc=$?
check "Fc1. CLAUDE_PROJECT_DIR=a standalone checkout: $UNREADABLE_COMMAND is denied (got $rc: '$(cat "$TMP/hook.out")')" \
  '[[ $rc -eq 0 ]] && grep -qF "$DENY_DECISION" "$TMP/hook.out"'
check "Fc2. ... nothing written there" '[[ "$(tree_state "$WT2")" == "$before" ]]'
fc_check="$(self_check "$WT2")"; rc=$?
check "Fc3. ... and --self --check reports $STATUS_IN_SYNC (got $rc: '$fc_check')" \
  '[[ $rc -eq 0 && "$fc_check" == "$STATUS_IN_SYNC"* ]]'
check "F4. no payload named a session, so the hook kept no counter anywhere" \
  '[[ -z "$(ls -A "$HOOK_TMP")" ]]'

# ── G. a resumed gate still checks the settings file ─────────────────────────
# E5 left the generated bytes in the standalone worktree; F did not touch it. Each run
# below sets GATE_RESUME=1 itself. The file is tracked, so deleting or drifting the working
# copy also moves the tree sha the resume keys on; G4 is what shows record_fresh holds.
python3 -B "$WT/hooks/wire-settings.py" --self --repo "$WT" --write >/dev/null 2>&1
run_gate_resumed "$WT"
run_gate_resumed "$WT"
check "G1. under GATE_RESUME=1 the settings check passes on the generated file, twice (got '$(gate_exit "$WT")')" \
  '[[ "$(gate_exit "$WT")" == "0" ]]'
rm -f "$WT/$SETTINGS_REL"
run_gate_resumed "$WT"
check "G2. ... and still FAILS when the working copy is then deleted (got '$(gate_exit "$WT")')" \
  '[[ "$(gate_exit "$WT")" == "1" ]]'
mkdir -p "$WT/$SETTINGS_DIR_REL"
printf '{}\n' > "$WT/$SETTINGS_REL"
run_gate_resumed "$WT"
check "G3. ... and when it has drifted (got '$(gate_exit "$WT")')" '[[ "$(gate_exit "$WT")" == "1" ]]'
settings_records="$(find "$WT/$GATE_STATE_REL" -name "$SETTINGS_STATE_NAME*" 2>/dev/null)"
check "G4. ... and no gate-state record was ever written for that check (got '$settings_records')" \
  '[[ -d "$WT/$GATE_STATE_REL" && -z "$settings_records" ]]'
python3 -B "$WT/hooks/wire-settings.py" --self --repo "$WT" --write >/dev/null 2>&1

if (( fails )); then
  echo "self-settings: $fails FAILED"
  exit 1
fi
echo "self-settings: all passed"
